### ISSUE TITLE
Avast blocks most of the subpages of scikit-image.org

### ISSUE THREAD

**Issue by bauerdavid** [scikit-image/skimage-web#100]
I wanted to check something in the documentation, but Avast Antivirus blocked the connection, due to "HTML:Script-inf [Susp]" infection. After that I checked all subpages, and got the same warning. This happens on all of the "Installation", "Gallery" and the "Documentation" subpages, but not with "Community".
Last time I visited the documentation page was around a week ago, and I could open it with no issue.

**Comment by jni** [comment]
@bauerdavid sorry, I'm confused by your message, specifically, "around a week ago, [...] I could open it with no issue" — does this mean the issue has been resolved, or...?

I don't have any ideas here because I don't use Avast so I don't know what they are alleging we are doing wrong.

As a side note, they were [recently fined for selling user browsing data](https://www.infosecurity-magazine.com/news/avast-fine-selling-browser-data/), which seems like a good reason to switch, if blocking skimage docs wasn't enough. 😂 From my reading of the article, they deny that the data was not properly anonymised, not that they collected the data in the first place. 🤦

**Comment by jni** [comment]
I'll CC @stefanv, @mkcor, and @lagru since this repo has less visibility than the others and they might miss this. On the other hand I haven't been keeping up with maintenance recently so maybe there has been a recent change to the website that I've missed and that could explain this.

**Comment by stefanv** [comment]
Our websites are generated programmatically from source, so unless a malicious PR escaped review, this is very likely a false alarm.

Please file an issue or post on the Avast user forum so they can investigate why our site is triggering their alert. See, e.g.,

https://forum.avast.com/index.php?topic=323872.0

**Comment by bauerdavid** [comment]
Aaaand it's gone... I don't know what caused this, but now it's working fine. Sorry for the blind alarm!
@jni wow, I didn't hear about it, thanks for the info!
